apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prom-data
  namespace: monitoring
  labels:
    app: prometheus-deployment
spec:
  storageClassName: csi-cinder-classic
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi